apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-ds
  namespace: kube-system
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        image: gcr.io/kubernetes-helm/tiller:v2.4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      volumes: null

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-ds
  namespace: kube-system
spec:
  ports:
  - name: tiller
    nodePort: 0
    port: 44134
    protocol: ""
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
  clusterIP: None
status:
  loadBalancer: {}
---
